### ISSUE TITLE
Error building for Windows 32 bits

### ISSUE THREAD

**Issue by Airdoggo** [AlexandreLamure/OM3D#1]
The file graphics.cpp is not able to compile when using MSVC x86.

The problem is in the following function :
https://github.com/AlexandreLamure/OM3D/blob/9a3ec249d9ce52fb356cf0797d6d3a0bba25b560/TP/src/graphics.cpp#L12

The 'sev' argument should have the 'GLenum' type and not the 'GLuint' type, as those two types differ on this particular architecture.

**Comment by gan74** [comment]
Should be fixed by commit a6eaa3bebdc7bebcfa1fdded9e2c71abaf65a288
